### ISSUE TITLE
There's a second version, which should be a second guide.

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-reactive-rest-service#1]
The version in this repository is functional in nature. Per a suggestion from Rossen, I also wrote an annotation-based version. That's in my own repository for this project, under the annotation-based branch: https://github.com/Buzzardo/gs-reactive-rest-service/tree/annotation-based

That should become a new guide. 

WARNING: It needs to be reviewed by people who know that content well.

**Comment by dsyer** [comment]
LGTM. I guess the `Quotation` has a separate `Value` because of the structure of the target data in https://gturnquist-quoters.cfapps.io/api/? Maybe the declaration could be nested inside `Quotation`?

The test needs to be fixed.

**Comment by ahndmal** [comment]
Hello @Buzzardo , @dsyer !

Can you please tell if this issue is still active and there can be added the second guide for Reactive based on @annotations, not in functional style?
Sorry if I missed smth and it already exists - then can you please suggest where it is.

Thanks!

**Comment by dsyer** [comment]
I think it would be easier to start again with the conversion to annotations (too much has diverged since Jay did that revision). It's fairly easy to do. IMO the annotations should be the "main" `gs-reactive-rest-service`, and we should add a new one with the contents of this repo and a`-fn` suffix.

Or we could explain more fully in the existing guide how to achieve the same with annotations (hint: take the gs-rest-service guide and change the classpath to swap `webmvc` for `webflux`).

**Comment by ahndmal** [comment]
Hello @dsyer ,
Thank you for the explanation! Yes, this seems to be a good solution :)
